{{- if and .Values.backend.enabled .Values.autoscaling.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "paddledock.fullname" . }}-backend
  labels:
    {{- include "paddledock.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "paddledock.fullname" . }}-backend
  minReplicas: {{ .Values.autoscaling.backend.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.backend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.backend.targetCPUUtilizationPercentage }}
{{- end }}
