apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paddledock.fullname" . }}-env
  labels:
    {{- include "paddledock.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: redis://{{ include "paddledock.redisHost" . }}:{{ .Values.redis.port }}/0
